### ISSUE TITLE
作者你好，这个库可以离线人脸识别吗，不是离线采集

### ISSUE THREAD

**Issue by Sam1141968878** [Symous/react-native-face-recognition#1]

**Comment by Symous** [comment]
@liguanhan 你好，这个库使用的是百度AI的人脸识别，目前我采用的模式是离线采集 + 在线识别（调用百度人脸时候识别的Web API），如果你要实现纯离线的话，建议你使用虹软的人脸识别。

**Comment by Sam1141968878** [comment]
作者你好，虹软的人脸识别目前也没用react-native的版本，想找一个react-native的纯离线版本

**Comment by Symous** [comment]
@liguanhan 我之前也找过，没有特别现成的RN插件，我才自己封装的这个基于百度的。
